# Pull Image

# Set your workdir

# Add some packets (do not touch this line)

# Import the requirement

# Install the packets

# Expose the app port (5000)

# Import the app

# Define the command at container startup
