# Select the image (version node version 14)

# Define a working directory

# Copy and install packets

# Import app in container

# Defines environment variables

# Expose the port

# Define the command which needs to be executed at container start-up
