# Pull Image (python v3.7 alpine)

# Set your workdir

# Define your env var

# Add some packets (do not touch this line)

# Import the requirement

# Install the packets

# Expose the app port (5000)

# Import the app

# Define the command at container startup
